# Generated by Django 6.0.6 on 2026-06-16 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnansweredQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='unanswered_queries', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'Unanswered Query',
                'verbose_name_plural': 'Unanswered Queries',
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UnansweredQueries',
        ),
    ]
