# Generated by Django 6.0.6 on 2026-08-09 12:31

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_unansweredquery_delete_unansweredqueries'),
        ('core', '0011_remove_project_unique_domain_per_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unansweredquery',
            name='client',
        ),
        migrations.AddField(
            model_name='unansweredquery',
            name='project',
            field=models.ForeignKey(default=uuid.uuid4(), editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='unanswered_queries', to='core.project', verbose_name='project'),
            preserve_default=False,
        ),
    ]
