# Generated by Django 6.0.6 on 2026-07-29 11:01

import django.core.validators
import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_client_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, help_text='Max Length is 255 Characters.', max_length=255, null=True)),
                ('doc_id', models.CharField(max_length=255)),
                ('file_raw', models.FileField(help_text='PDF/TXT/MD/DOCX - max file size 10MB', upload_to=documents.models.project_file_path, validators=[documents.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'md', 'docx'])])),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA256 hash of the file. Raw key is never stored.', max_length=64)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('chunk_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('created', 'Created'), ('duplicate', 'Duplicate'), ('updated', 'Updated'), ('failed', 'Failed'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='received', max_length=10)),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
            options={
                'ordering': ['doc_id', 'status'],
                'indexes': [models.Index(fields=['project', 'doc_id'], name='documents_d_project_05af49_idx'), models.Index(fields=['status'], name='documents_d_status_07369e_idx')],
            },
        ),
    ]
