# Generated by Django 6.0.6 on 2026-06-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='api_key_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of the API key. Raw key is never stored.', max_length=64, null=True),
        ),
    ]
