# Generated by Django 6.0.6 on 2026-06-26 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_managers_remove_client_api_key_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('widget_enabled', models.BooleanField(default=True)),
                ('api_key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('api_key_last_used', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'name'], name='core_projec_client__33cf98_idx'), models.Index(fields=['is_active'], name='core_projec_is_acti_612de5_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'domain'), name='unique_domain_per_project')],
            },
        ),
    ]
