# Generated by Django 6.0.6 on 2026-07-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
    ]
