# Generated by Django 6.0.6 on 2026-08-01 20:30

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_client_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bot_display_name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='bubble_position',
            field=models.CharField(choices=[('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], default='bottom-right', max_length=12),
        ),
        migrations.AddField(
            model_name='project',
            name='greeting_message',
            field=models.TextField(default='Welcome! How may I assist you?', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_raw',
            field=models.ImageField(blank=True, help_text='JPG/PNG/SVG/WEBP - max file size 1 MB', null=True, upload_to=core.models.logo_file_path, validators=[core.models.validate_logo_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='project',
            name='theme_color',
            field=models.JSONField(default=core.models.default_widget_theme),
        ),
    ]
