# Generated by Django 6.0.6 on 2026-08-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_otp_cleanup_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
