# Generated by Django 6.0.6 on 2026-08-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_is_deleted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_domain_per_project',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('client', 'domain'), name='unique_domain_per_client_active'),
        ),
    ]
