# Generated by Django 6.0.6 on 2026-08-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_project_unique_domain_per_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='groq_api_key_encrypted',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='groq_api_key_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
